# Generated by Django 4.2.27 on 2026-01-05 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronym', models.CharField(blank=True, max_length=100)),
                ('full_name', models.CharField(blank=True, help_text='Combined name+surname+patronym', max_length=300)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='TRUE = Currently Logged In, FALSE = Logged Out')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('banned', 'Banned'), ('deleted', 'Deleted')], default='active', help_text='To handle admin bans separate from login status', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(help_text='Permission codename, e.g., task_create, task_delete_any', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human readable description of what this allows')),
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'db_table': 'permissions',
                'ordering': ['codename'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name: administrator, moderator, user', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the hierarchy rank')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the connection')),
                ('user_agent', models.TextField(help_text='Browser/Device details string')),
                ('screen_size', models.CharField(blank=True, help_text='Screen size, e.g., 1920x1080', max_length=20)),
                ('timezone', models.CharField(blank=True, default='UTC', help_text='Timezone, e.g., UTC, America/New_York', max_length=50)),
                ('language', models.CharField(blank=True, default='en-US', help_text='Language, e.g., en-US, fr-FR', max_length=10)),
                ('connection_number', models.IntegerField(default=1, help_text='A sequence number or ID for this specific connection')),
                ('extra_metadata', models.JSONField(blank=True, default=dict, help_text='JSON: To store other parameters safely')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the login happened')),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Updated on every request to track timeouts')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user session',
                'verbose_name_plural': 'user sessions',
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(db_column='permission_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.permission')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role')),
            ],
            options={
                'verbose_name': 'role permission',
                'verbose_name_plural': 'role permissions',
                'db_table': 'role_permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
